analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.89316296717152
title: Recruited To Recruit
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.5266707967966795
  brandStrength: 0.3070586260873824
  rhythmicContrast: 0.8824936056043953
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  lightness: 0.9942882428877056
purpose: []
favicon: null
name: RecruitedToRecruit
typography_spectrum: 0.7958351075649261
