name: RecruitedToRecruit
favicon: null
layout_spectrum: 0.89316296717152
typography_spectrum: 0.7958351075649261
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.30705862608738244
  lightness: 0.9942882428877056
  saturation: 0.5266707967966795
  rhythmicContrast: 0.8824936056043953
purpose: []
